"""
db_setup.py
------------
Loads data/sales_data.csv into a local SQLite database (analytics.db).
SQLite is used here purely so the project runs anywhere with zero setup.
Swap the connection string in app.py if you want to point this at
Postgres/MySQL instead -- the SQL generated by nl_to_sql.py is plain
ANSI SQL so it should work with minimal changes.

Run:
    python db_setup.py
"""

import sqlite3
import pandas as pd

DB_PATH = "analytics.db"
CSV_PATH = "data/sales_data.csv"
TABLE_NAME = "sales"


def build_database():
    df = pd.read_csv(CSV_PATH, parse_dates=["order_date"])

    conn = sqlite3.connect(DB_PATH)
    df.to_sql(TABLE_NAME, conn, if_exists="replace", index=False)

    # a couple of indexes so the demo doesn't feel sluggish once questions
    # start filtering/grouping on these columns
    cur = conn.cursor()
    cur.execute(f"CREATE INDEX IF NOT EXISTS idx_region ON {TABLE_NAME}(region)")
    cur.execute(f"CREATE INDEX IF NOT EXISTS idx_date ON {TABLE_NAME}(order_date)")
    conn.commit()
    conn.close()
    print(f"Loaded {len(df)} rows into {DB_PATH} -> table '{TABLE_NAME}'")


if __name__ == "__main__":
    build_database()
